### ISSUE TITLE
Chart Delays After a Specific Finish Date

### ISSUE THREAD

**Issue by JoyceEvans** [takuya0206/ganttchart_generator#4]
Hello, 

There is an issue on the 2019 planning since the following date : 08/04/2019. 
There is a delay of one day since the 8th of april. 
The monday 8th of april appears on sunday on the planning and then all the dates are delayed. 
Could you please correct this bug ? 

Thank you in advance

**Comment by takuya0206** [comment]
@JoyceEvans 
I have changed the logic for calculation of date. Now it is simply adding 7 days to the base date on your spreadsheet. Could you activate your gantt chart by using "Change Start Date and Chart Width" and check how it works? I hope this change can solve your problem.

**Comment by JoyceEvans** [comment]
Hello, 

I have tried to activate « Change Start Date and Chart Width » but the delay is still her. 



Thank you for your return. 

Joyce  
_____________________________________

Joyce Evans
Département digital

Tél : +33. (0)1 55 33 11 50

adfinitas
révélateur d’engagement

132 Rue La Fayette
75010 PARIS
France

Retrouvez-nous sur www.adfinitas.fr <http://www.adfinitas.fr/>
Facebook <https://fr-fr.facebook.com/adfinitas.relationship.fundraising/> et linkedIn <https://www.linkedin.com/company/adfinitas>
_____________________________________

**Comment by takuya0206** [comment]
@JoyceEvans As a workaround, could you manually change the date? The following dates will also change since formulas in Google Spreadsheet are used now.

**Comment by JoyceEvans** [comment]
Hey, 
Sorry but I don’t understand which date should I change and how. 
The finish date (2019/04/01) of the task should be on monday instead of sunday… 



Thank you, 
Joyce 
_____________________________________

Joyce Evans
Département digital

Tél : +33. (0)1 55 33 11 50

adfinitas
révélateur d’engagement

132 Rue La Fayette
75010 PARIS
France

Retrouvez-nous sur www.adfinitas.fr <http://www.adfinitas.fr/>
Facebook <https://fr-fr.facebook.com/adfinitas.relationship.fundraising/> et linkedIn <https://www.linkedin.com/company/adfinitas>
_____________________________________

**Comment by takuya0206** [comment]
@JoyceEvans Oh, there must be misunderstanding. Okay, let me start from the beginning again. Could you invite me (sub.takuya@gmail.com) to your spreadsheet? I will investigate if there is a bug or any work around.

**Comment by JoyceEvans** [comment]
I have just send you an invitation. 
_____________________________________

Joyce Evans
Département digital

Tél : +33. (0)1 55 33 11 50

adfinitas
révélateur d’engagement

132 Rue La Fayette
75010 PARIS
France

Retrouvez-nous sur www.adfinitas.fr <http://www.adfinitas.fr/>
Facebook <https://fr-fr.facebook.com/adfinitas.relationship.fundraising/> et linkedIn <https://www.linkedin.com/company/adfinitas>
_____________________________________

**Comment by takuya0206** [comment]
@JoyceEvans I have checked your spreadsheet. I guess daylight saving time causes this problem. As a workaround, you can solve this by adding balance values like 1:00 as the following picture shown.
 
<img width="1323" alt="2019-02-20 23 21 04" src="https://user-images.githubusercontent.com/22774683/53098100-41e56600-3566-11e9-9f0c-5cd5bf345c82.png">

**Comment by JoyceEvans** [comment]
Thank you, it is working ! 

_____________________________________

Joyce Evans
Département digital

Tél : +33. (0)1 55 33 11 50

adfinitas
révélateur d’engagement

132 Rue La Fayette
75010 PARIS
France

Retrouvez-nous sur www.adfinitas.fr <http://www.adfinitas.fr/>
Facebook <https://fr-fr.facebook.com/adfinitas.relationship.fundraising/> et linkedIn <https://www.linkedin.com/company/adfinitas>
_____________________________________

**Comment by takuya0206** [comment]
@JoyceEvans I'm happy to hear that it works. I have changed the title of this issue and closed since there is a workaround at least.

**Comment by JoyceEvans** [comment]
Hey, 

I am contacted you as all my 2019 planning are not working anymore. 
When I create a new task and selecte dates for « Plannned start » and « Planned Fish »  the box on the planning sheet is not created. 
Could you please check and tell me what the problem is :  https://docs.google.com/spreadsheets/d/1J8AFiJoHiwNMqT8TjYgx9K85H7TAbHxsqtWvi3kdyqg/edit?usp=sharing <https://docs.google.com/spreadsheets/d/1J8AFiJoHiwNMqT8TjYgx9K85H7TAbHxsqtWvi3kdyqg/edit?usp=sharing>

Thank you in advance. 

Best regards, 
Joyce 
_____________________________________

Joyce Evans
Département digital

Tél : +33. (0)1 55 33 11 50

adfinitas
révélateur d’engagement

132 Rue La Fayette
75010 PARIS
France

Retrouvez-nous sur www.adfinitas.fr <http://www.adfinitas.fr/>
Facebook <https://fr-fr.facebook.com/adfinitas.relationship.fundraising/> et linkedIn <https://www.linkedin.com/company/adfinitas>
_____________________________________
